[project]
name = "mar-migrate"
version = "0.1.0"
description = "Alembic マイグレーション (my-aicoding-recipe)"
readme = "README.md"
authors = [
    { name = "Masaki Kobayashi", email = "bayashi.cl@gmail.com" }
]
requires-python = ">=3.14"
dependencies = [
    "alembic>=1.18.4",
    "mar-api",
    "psycopg[binary]>=3.3.4",
]

[build-system]
requires = ["uv_build>=0.11.15,<0.12.0"]
build-backend = "uv_build"

[tool.uv.sources]
mar-api = { workspace = true, editable = true }
